[package]
name = "rlmlua"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.0"
mlua = {version = "0.10.0", features = ["lua54", "vendored"]}

[lib]
name = "rlmlua"
crate-type = ["cdylib"]
