[package]
name = "rlmlua"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = { version = "5.5.1", features = ["custom_frame_control"] }
mlua = {version = "0.11", features = ["lua54", "module"]}

[lib]
name = "rlmlua"
crate-type = ["cdylib"]
